# apiVersion: apps/v1
apiVersion: extensions/v1beta1

kind: Deployment
metadata:
  name:  my-falsk
  namespace: flask-web-app
  labels:
    name:  my-flask
    app: front-end
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  my-flask
    spec:
      containers:
      - image:  hamidgholami/flaskcd:latest
        name:  my-flask-img
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        # env:
        # - name:  ENVVARNAME
        #   value:  ENVVARVALUE       
        ports:
        - containerPort:  8080
          name:  my-flask-port
        volumeMounts:
        - mountPath: /data
          name: my-flask-data
      volumes:
        - name: my-flask-data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always